import express from "express";
import Question from "../models/question.js";
import Quiz from "../models/quiz.js";
import generateQuiz from "../services/geminiService.js";

const router = express.Router();

router.post("/generate", async (req, res) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: "Authorization required" });
    }

    if (!["admin", "instructor"].includes(req.user.role)) {
      return res.status(403).json({ error: "Only admins and instructors can generate quizzes" });
    }

    const { prompt, timeLimit = 10, availableFor = 60 } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: "prompt is required" });
    }

    const generatedQuiz = await generateQuiz(prompt);

    if (!generatedQuiz?.title || !Array.isArray(generatedQuiz.questions) || generatedQuiz.questions.length === 0) {
      return res.status(400).json({ error: "Invalid quiz generated by AI" });
    }

    const quiz = await Quiz.create({
      title: generatedQuiz.title,
      description: generatedQuiz.description || "",
      timeLimit,
      availableFor,
      isPublished: false,
      createdBy: req.user._id,
    });

    const questionDocs = generatedQuiz.questions.map((question) => ({
      quizId: quiz._id,
      questionText: question.question,
      options: question.options,
      correctOption: question.correctAnswer,
    }));

    await Question.insertMany(questionDocs);

    res.status(201).json({
      message: "Quiz generated and saved successfully",
      quizId: quiz._id,
      quiz,
      questionsCreated: questionDocs.length,
      generatedQuiz,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: "Failed to generate quiz",
    });
  }
});

export default router;
